// frontend/src/pages/PlanTrip.jsx
// ✅ BUGS FIXED & UPGRADES:
//   1. PDF Theme: Premium Creamy White (#FDFBF7) & Warm Gold.
//   2. PDF Layout: Compressed aggressively to strictly 2-3 pages maximum.
//   3. PDF Safety: safeString() prevents NaN coordinate crashes.
//   4. MapView Component: Using Custom iframe MapView with dynamic destination. Removed dead Leaflet code.
//   5. Skeletons: Added Premium TripSkeleton for loading states.

import React, { useState, useEffect } from "react";
import { useLocation, useNavigate } from "react-router-dom";
import api from "../lib/api";
import jsPDF from "jspdf";

// 🔥 IMPORT YOUR CUSTOM MAP COMPONENT
import MapView from "../components/MapView";

// ✅ ADDED SKELETON IMPORT
import { TripSkeleton } from "../components/Skeletons";

function parseTripData(raw) {
  if (!raw) return null;
  if (typeof raw === "object") return raw;
  try {
    const clean = raw
      .replace(/^```json\s*/i, "")
      .replace(/^```\s*/i, "")
      .replace(/```\s*$/i, "")
      .trim();
    return JSON.parse(clean);
  } catch {
    return null;
  }
}

// 🔥 BULLETPROOF DATA PARSER FOR PDF
const safeString = (val) => {
  if (val === null || val === undefined) return "—";
  if (typeof val === "string") return val;
  if (Array.isArray(val)) return val.map(v => typeof v === 'object' ? Object.values(v).join(' ') : v).join(", ");
  if (typeof val === "object") return Object.values(val).join(", ");
  return String(val);
};

export default function PlanTrip() {
  const { state } = useLocation();
  const navigate  = useNavigate();

  const destination = state?.destination || "";
  const budget      = state?.budget      || "";
  const startDate   = state?.checkin     || "";
  const endDate     = state?.checkout    || "";

  const dayCount = startDate && endDate
    ? Math.max(1, Math.round((new Date(endDate) - new Date(startDate)) / 86400000))
    : 0;

  const [tripData, setTripData]         = useState(null);
  const [editMode, setEditMode]         = useState(false);
  const [editableTrip, setEditableTrip] = useState(null);
  const [loading, setLoading]           = useState(true);
  const [error, setError]               = useState("");
  const [showSuccess, setShowSuccess]   = useState(false);
  const [showToast, setShowToast]       = useState(false);
  const [openDays, setOpenDays]         = useState({ 0: true });
  const [activeTab, setActiveTab]       = useState("Itinerary");

  useEffect(() => {
    if (!state) { navigate("/"); return; }

    const fetchAI = async () => {
      try {
        setLoading(true);
        setError("");
        setShowSuccess(false);
        setShowToast(false);

        const res = await api.post("/api/ai", { destination, budget, startDate, endDate });
        const raw = res.data.data || "";
        const parsed = parseTripData(raw);
        setTripData(parsed);
        setShowSuccess(true);

        setTimeout(() => {
          setShowSuccess(false);
          setShowToast(true);
          setTimeout(() => setShowToast(false), 2000);
        }, 1500);
      } catch (err) {
        setError(
          err?.response?.data?.error?.message ||
          err?.response?.data?.message ||
          "AI generation failed. Check your backend logs."
        );
      } finally {
        setLoading(false);
      }
    };

    fetchAI();
  // eslint-disable-next-line react-hooks/exhaustive-deps
  }, []);

  useEffect(() => {
    if (tripData) {
      setEditableTrip(JSON.parse(JSON.stringify(tripData)));
    }
  }, [tripData]);

  const toggleDay = (dayKey) =>
    setOpenDays(prev => ({ ...prev, [dayKey]: !prev[dayKey] }));

  // 📄 COMPACT CREAMY-WHITE PDF GENERATOR (MAX 2-3 PAGES)
  const downloadPDF = () => {
    if (!tripData) return;

    const doc = new jsPDF({ unit: "mm", format: "a4" });
    const PW = 210, PH = 297;
    const ML = 16, MR = 16;
    const CW = PW - ML - MR; 

    const safeDayCount = (startDate && endDate)
      ? Math.max(1, Math.round((new Date(endDate) - new Date(startDate)) / 86400000))
      : (tripData.days?.length || 0);

    const rs = (val) => `Rs. ${val}`;

    const rgb = (hex) => {
      const h = hex.replace("#","");
      return [parseInt(h.slice(0,2),16), parseInt(h.slice(2,4),16), parseInt(h.slice(4,6),16)];
    };
    
    const fill   = (hex) => doc.setFillColor(...rgb(hex));
    const stroke = (hex) => doc.setDrawColor(...rgb(hex));
    const color  = (hex) => doc.setTextColor(...rgb(hex));
    const lw     = (w)   => doc.setLineWidth(w);

    let y = 0;
    let pageNum = 1;

    const addFooter = () => {
      color("#9CA3AF"); doc.setFont("helvetica","normal"); doc.setFontSize(8);
      doc.text("Generated by wander.ai", ML, PH - 8);
      doc.text(`Page ${pageNum}`, PW - MR, PH - 8, { align: "right" });
    };

    const addPage = () => {
      addFooter();
      doc.addPage();
      pageNum++;
      fill("#FDFBF7"); doc.rect(0, 0, PW, PH, "F"); 
      color("#9CA3AF"); doc.setFont("helvetica","normal"); doc.setFontSize(8);
      doc.text(`Wander.ai • ${destination.toUpperCase()}`, ML, 10);
      y = 18;
    };

    const needSpace = (h) => {
      if (y + h > PH - 15) {
        addPage();
        return true;
      }
      return false;
    };

    const sectionHead = (text, accentHex = "#D97706") => {
      needSpace(12);
      color(accentHex); doc.setFont("helvetica","bold"); doc.setFontSize(10);
      doc.text(text.toUpperCase(), ML, y);
      y += 2;
      stroke(accentHex); lw(0.5); doc.line(ML, y, ML + CW, y);
      y += 6;
    };

    // ── PAGE 1: COMPACT HEADER (Creamy Theme) ──
    fill("#FDFBF7"); doc.rect(0, 0, PW, PH, "F"); 
    
    // Subtle background warm shapes
    fill("#FDE68A"); doc.circle(PW, 0, 40, "F"); 
    fill("#FEF3C7"); doc.circle(0, PH, 50, "F"); 
    
    // Light overlay to keep text readable
    doc.setGState(new doc.GState({ opacity: 0.2 }));
    fill("#FDFBF7"); doc.rect(0, 0, PW, PH, "F");
    doc.setGState(new doc.GState({ opacity: 1 }));

    y = 22;
    color("#B45309"); doc.setFont("helvetica","bold"); doc.setFontSize(8);
    doc.text("WANDER.AI • PERSONALIZED ITINERARY", ML, y);
    
    y += 10;
    color("#111827"); doc.setFontSize(28);
    doc.text(destination.toUpperCase(), ML, y, { maxWidth: CW });
    
    y += 8;
    color("#4B5563"); doc.setFont("helvetica","normal"); doc.setFontSize(11);
    doc.text(`${startDate || "—"} to ${endDate || "—"}  •  ${safeDayCount} Days  •  ${rs(budget)}`, ML, y);

    y += 6;
    stroke("#D1D5DB"); lw(0.3); doc.line(ML, y, ML + CW, y);
    y += 8;

    // ── TRIP OVERVIEW / BUDGET (2-Column Dense Grid) ──
    let budgetEntries = [];
    if (tripData.budgetBreakdown) {
      if (Array.isArray(tripData.budgetBreakdown)) {
        budgetEntries = tripData.budgetBreakdown.map(item => [safeString(item.category || item.name || "Item"), safeString(item.cost || item.amount || "—")]);
      } else if (typeof tripData.budgetBreakdown === 'object') {
        budgetEntries = Object.entries(tripData.budgetBreakdown);
      }
    }

    if (budgetEntries.length > 0 || tripData.bestTimeToVisit) {
      sectionHead("Trip Overview", "#D97706");
      
      if (tripData.bestTimeToVisit) {
        color("#111827"); doc.setFont("helvetica","bold"); doc.setFontSize(9);
        doc.text("Best Time to Visit:", ML, y);
        color("#4B5563"); doc.setFont("helvetica","normal");
        doc.text(safeString(tripData.bestTimeToVisit), ML + 30, y);
        y += 6;
      }

      if (budgetEntries.length > 0) {
        const halfW = (CW - 4) / 2;
        budgetEntries.forEach(([key, val], idx) => {
          const isLeft = idx % 2 === 0;
          if (isLeft) needSpace(8);
          const xOff = ML + (isLeft ? 0 : halfW + 4);
          const isTotal = key.toLowerCase().includes("total");

          fill(isTotal ? "#FEF3C7" : "#FFFFFF"); 
          stroke("#E5E7EB"); lw(0.2);
          doc.roundedRect(xOff, y, halfW, 7, 1, 1, "FD");

          color(isTotal ? "#92400E" : "#4B5563"); 
          doc.setFont("helvetica", isTotal ? "bold" : "normal"); doc.setFontSize(8);
          doc.text(safeString(key).replace(/([A-Z])/g," $1").trim(), xOff + 3, y + 4.8);

          color(isTotal ? "#B45309" : "#111827"); doc.setFont("helvetica","bold");
          doc.text(safeString(val).replace(/₹/g, "Rs. "), xOff + halfW - 3, y + 4.8, { align:"right" });

          if (!isLeft || idx === budgetEntries.length - 1) y += 8;
        });
      }
      y += 4;
    }

    // ── HIGH-DENSITY ITINERARY ──
    sectionHead("Day-by-Day Itinerary", "#D97706");
    const daysArr = Array.isArray(tripData.days) ? tripData.days : [];

    daysArr.forEach((day, i) => {
      const mLines = doc.splitTextToSize(safeString(day.morning), CW - 24);
      const aLines = doc.splitTextToSize(safeString(day.afternoon), CW - 24);
      const eLines = doc.splitTextToSize(safeString(day.evening), CW - 24);
      
      const cardH  = 10 + (mLines.length + aLines.length + eLines.length) * 4.2;
      needSpace(cardH + 4);

      fill("#FFFFFF"); stroke("#E5E7EB"); lw(0.3);
      doc.roundedRect(ML, y, CW, cardH, 2, 2, "FD");
      
      fill("#F59E0B"); doc.roundedRect(ML, y, 3, cardH, 1, 1, "F");
      doc.rect(ML + 1, y, 2, cardH, "F");

      color("#B45309"); doc.setFont("helvetica","bold"); doc.setFontSize(9);
      doc.text(`DAY ${day.day}:`, ML + 6, y + 6);
      
      color("#111827");
      doc.text(safeString(day.title) || `Exploring ${destination}`, ML + 22, y + 6, { maxWidth: CW - 26 });

      let dy = y + 11.5;
      const slots = [
        { label:"MORNING:",   lines: mLines },
        { label:"AFTERNOON:", lines: aLines },
        { label:"EVENING:",   lines: eLines },
      ];
      slots.forEach(({ label, lines }) => {
        color("#D97706"); doc.setFont("helvetica","bold"); doc.setFontSize(7);
        doc.text(label, ML + 6, dy);
        
        color("#374151"); doc.setFont("helvetica","normal"); doc.setFontSize(8);
        doc.text(lines, ML + 24, dy);
        dy += lines.length * 4.2 + 1;
      });
      y += cardH + 4;
    });

    // ── COMPACT FOOD & STAYS ──
    const hasStays = tripData.whereToStay && Object.keys(tripData.whereToStay).length > 0;
    const mustEatArr = Array.isArray(tripData.mustEat) ? tripData.mustEat : (typeof tripData.mustEat === "string" ? [tripData.mustEat] : []);
    
    if (hasStays || mustEatArr.length > 0) {
      sectionHead("Food & Stays", "#D97706");

      if (hasStays) {
        const halfW = (CW - 4) / 2;
        const bLines = doc.splitTextToSize(safeString(tripData.whereToStay.budget || tripData.whereToStay.budgetOption), halfW - 6);
        const mLines = doc.splitTextToSize(safeString(tripData.whereToStay.midRange || tripData.whereToStay.midRangeOption), halfW - 6);
        
        const maxH = Math.max(bLines.length, mLines.length) * 4.5 + 9;
        needSpace(maxH + 4);

        fill("#FFFFFF"); stroke("#E5E7EB"); lw(0.2);
        doc.roundedRect(ML, y, halfW, maxH, 2, 2, "FD");
        color("#B45309"); doc.setFont("helvetica","bold"); doc.setFontSize(8);
        doc.text("BUDGET STAY", ML + 3, y + 5);
        color("#4B5563"); doc.setFont("helvetica","normal"); doc.setFontSize(8);
        doc.text(bLines, ML + 3, y + 9.5);

        doc.roundedRect(ML + halfW + 4, y, halfW, maxH, 2, 2, "FD");
        color("#B45309"); doc.setFont("helvetica","bold");
        doc.text("MID-RANGE STAY", ML + halfW + 7, y + 5);
        color("#4B5563"); doc.setFont("helvetica","normal");
        doc.text(mLines, ML + halfW + 7, y + 9.5);

        y += maxH + 4;
      }

      if (mustEatArr.length > 0) {
        needSpace(10);
        color("#111827"); doc.setFont("helvetica","bold"); doc.setFontSize(8);
        doc.text("MUST-TRY FOODS:", ML, y);
        y += 5;

        const cols = 3;
        const colW = CW / cols;
        mustEatArr.forEach((food, i) => {
          const isNewLine = i % cols === 0 && i !== 0;
          if (isNewLine) { y += 5; needSpace(6); }
          const xOff = ML + (i % cols) * colW;
          
          fill("#FEF3C7"); doc.circle(xOff + 2, y - 1, 1.5, "F");
          color("#374151"); doc.setFont("helvetica","normal"); doc.setFontSize(8);
          const truncated = safeString(food).length > 35 ? safeString(food).substring(0, 32) + "..." : safeString(food);
          doc.text(truncated, xOff + 5, y);
        });
        y += 6;
      }
    }

    // ── COMPACT TRAVEL TIPS ──
    const tipsArr = Array.isArray(tripData.travelTips) ? tripData.travelTips : (typeof tripData.travelTips === "string" ? [tripData.travelTips] : []);
    if (tipsArr.length > 0) {
      sectionHead("Essential Travel Tips", "#D97706");
      tipsArr.forEach((tip, i) => {
        const lines = doc.splitTextToSize(safeString(tip), CW - 8);
        needSpace(lines.length * 4.5 + 2);
        
        color("#D97706"); doc.setFont("helvetica","bold"); doc.setFontSize(8);
        doc.text(`0${i+1}`, ML, y);
        
        color("#374151"); doc.setFont("helvetica","normal");
        doc.text(lines, ML + 6, y);
        y += lines.length * 4.5 + 2;
      });
    }

    addFooter();
    doc.save(`${destination}-wander-ai-trip.pdf`);
  };

  // ─────────────────────────────── JSX ──────────────────────────────────
  return (
    <>
      <style dangerouslySetInnerHTML={{ __html: `
        @import url('[https://fonts.googleapis.com/css2?family=Space+Grotesk:wght@400;500;600;700&family=Playfair+Display:wght@700;900&family=DM+Sans:wght@400;500;600;700&display=swap](https://fonts.googleapis.com/css2?family=Space+Grotesk:wght@400;500;600;700&family=Playfair+Display:wght@700;900&family=DM+Sans:wght@400;500;600;700&display=swap)');

        /* Updated to warm, creamy tones to completely remove blue */
        .travel-vibe-bg { position:fixed; top:0; left:0; width:100vw; height:100vh; background:#FDFBF7; z-index:-1; overflow:hidden; }
        .orb-1 { position:absolute; top:-10%; left:-10%; width:50vw; height:50vw; background:radial-gradient(circle,rgba(245,158,11,0.2) 0%,rgba(255,255,255,0) 70%); filter:blur(80px); animation:float 20s ease-in-out infinite; }
        .orb-2 { position:absolute; bottom:-20%; right:-10%; width:60vw; height:60vw; background:radial-gradient(circle,rgba(16,185,129,0.15) 0%,rgba(255,255,255,0) 70%); filter:blur(90px); animation:float 25s ease-in-out infinite reverse; }
        .orb-3 { position:absolute; top:30%; left:30%; width:40vw; height:40vw; background:radial-gradient(circle,rgba(217,119,6,0.15) 0%,rgba(255,255,255,0) 70%); filter:blur(70px); animation:float 22s ease-in-out infinite alternate; }
        
        @keyframes float { 0%{transform:translate(0,0) scale(1)} 33%{transform:translate(5%,10%) scale(1.1)} 66%{transform:translate(-5%,5%) scale(0.9)} 100%{transform:translate(0,0) scale(1)} }
        @keyframes slideDown { 0%{opacity:0;transform:translate(-50%,-20px)} 100%{opacity:1;transform:translate(-50%,0)} }
        .animate-slideDown { animation:slideDown 0.4s ease-out forwards; }
        @keyframes slideUp { 0%{opacity:0;transform:translateY(20px)} 100%{opacity:1;transform:translateY(0)} }
        .animate-slideUp { animation:slideUp 0.4s ease-out forwards; }
        @keyframes popIn { 0%{transform:scale(0.8);opacity:0} 100%{transform:scale(1);opacity:1} }
        @keyframes bounceEmoji { 0%,100%{transform:translateY(0)} 50%{transform:translateY(-12px)} }
        @keyframes pulse { 0%,100%{opacity:1} 50%{opacity:.4} }
        @keyframes loadPulse { 0%,100%{opacity:1} 50%{opacity:.5} }
        .loading-pulse { animation:loadPulse 2s infinite; }

        .plan-trip-container {
          --font-head:'Playfair Display',Georgia,serif;
          --font-ui:'Space Grotesk',sans-serif;
          --surface:rgba(255,255,255,0.7); --surface-2:rgba(255,255,255,0.5); --surface-3:rgba(255,255,255,0.9);
          --border:rgba(0,0,0,0.08); --border-2:rgba(0,0,0,0.04);
          --text:#111827; --muted:#4B5563; --dim:#9CA3AF;
          --amber:#F59E0B; --amber-dim:rgba(245,158,11,0.15); --amber-text:#B45309;
          --emerald:#10B981; --emerald-dim:rgba(16,185,129,0.15); --emerald-text:#047857;
          --rose:#EF4444; --rose-dim:rgba(239,68,68,0.15);
          font-family:var(--font-ui); color:var(--text); font-size:14px; line-height:1.5;
          min-height:100vh; padding:20px; display:flex; justify-content:center; position:relative; z-index:1;
        }

        .shell { background:rgba(255,255,255,0.6); backdrop-filter:blur(24px); -webkit-backdrop-filter:blur(24px); width:100%; max-width:1200px; border-radius:16px; overflow:hidden; border:1px solid rgba(0,0,0,0.05); box-shadow:0 20px 50px rgba(0,0,0,0.04); display:flex; flex-direction:column; }

        .topbar { display:flex; align-items:center; justify-content:space-between; padding:0 20px; height:54px; background:var(--surface); border-bottom:1px solid var(--border); gap:12px; }
        .topbar-left { display:flex; align-items:center; gap:8px; }
        .wordmark { font-family:var(--font-ui); font-weight:700; font-size:15px; letter-spacing:0.02em; color:var(--text); }
        .wordmark span { color:var(--amber); }
        .divider-v { width:1px; height:20px; background:var(--border-2); }
        .breadcrumb { font-size:13px; color:var(--muted); display:flex; align-items:center; gap:6px; }
        .breadcrumb b { color:var(--text); font-weight:600; }
        .topbar-right { display:flex; align-items:center; gap:8px; }
        .tag { display:inline-flex; align-items:center; gap:5px; padding:4px 12px; border-radius:6px; font-size:11px; font-weight:700; letter-spacing:0.04em; text-transform:uppercase; }
        .tag-amber { background:var(--amber-dim); color:var(--amber-text); border:1px solid rgba(245,158,11,0.3); }
        .tag-emerald { background:var(--emerald-dim); color:var(--emerald-text); border:1px solid rgba(16,185,129,0.3); }
        .dot { width:6px; height:6px; border-radius:50%; background:var(--emerald); animation:pulse 2s infinite; }

        .layout { display:grid; grid-template-columns:260px 1fr; min-height:700px; flex:1; }
        .sidebar { background:var(--surface-2); border-right:1px solid var(--border); padding:24px 0; display:flex; flex-direction:column; gap:2px; }
        .sidebar-section { padding:0 20px 8px; margin-top:16px; }
        .sidebar-label { font-size:10px; font-weight:700; letter-spacing:0.12em; text-transform:uppercase; color:var(--dim); margin-bottom:12px; padding:0 4px; }
        .nav-item { display:flex; align-items:center; gap:12px; padding:9px 16px; border-radius:8px; font-size:13px; font-weight:500; color:var(--muted); cursor:pointer; transition:all .2s; margin:0 8px; }
        .nav-item:hover { background:rgba(255,255,255,0.7); color:var(--text); transform:translateX(4px); }
        .nav-item.active { background:var(--surface-3); color:var(--text); font-weight:600; }

        .trip-meta { margin:16px 20px 0; padding:16px; background:rgba(255,255,255,0.7); border-radius:12px; border:1px solid var(--border); }
        .trip-dest { font-family:var(--font-head); font-size:24px; font-style:italic; color:var(--text); margin-bottom:4px; text-transform:capitalize; }
        .trip-dates { font-size:12px; font-weight:500; color:var(--muted); margin-bottom:12px; }
        .trip-stat { display:flex; justify-content:space-between; align-items:center; padding:6px 0; border-bottom:1px solid rgba(0,0,0,0.04); }
        .trip-stat:last-child { border:none; padding-bottom:0; }
        .trip-stat-label { font-size:11px; color:var(--muted); font-weight:600; letter-spacing:.05em; text-transform:uppercase; }
        .trip-stat-val { font-size:13px; font-weight:700; color:var(--text); }

        .main { display:flex; flex-direction:column; overflow:hidden; }
        .page-header { padding:24px 32px 20px; border-bottom:1px solid var(--border); display:flex; align-items:flex-start; justify-content:space-between; gap:16px; flex-wrap:wrap; }
        .page-title { font-family:var(--font-head); font-size:36px; font-weight:400; color:var(--text); line-height:1.1; margin-bottom:6px; }
        .page-title span { font-style:italic; color:var(--amber-text); text-transform:capitalize; }
        .page-sub { font-size:13px; color:var(--muted); font-weight:500; }

        .btn-cluster { display:flex; flex-wrap:wrap; align-items:center; gap:10px; margin-top:4px; }
        .btn-pdf { padding:8px 16px; border-radius:10px; font-size:13px; font-weight:700; cursor:pointer; background:rgba(255,255,255,0.9); color:#111827; border:1px solid rgba(0,0,0,0.1); font-family:var(--font-ui); transition:transform 0.15s,box-shadow 0.15s; }
        .btn-pdf:hover { transform:translateY(-1px); box-shadow:0 4px 12px rgba(0,0,0,0.05); }
        .btn-dashboard { padding:8px 16px; border-radius:10px; font-size:13px; font-weight:700; cursor:pointer; background:rgba(255,255,255,0.7); color:#374151; border:1px solid rgba(0,0,0,0.1); font-family:var(--font-ui); transition:transform 0.15s,background 0.15s; }
        .btn-dashboard:hover { background:rgba(255,255,255,1); transform:translateY(-1px); }
        .btn-book { padding:8px 20px; border-radius:10px; font-size:13px; font-weight:800; cursor:pointer; background:linear-gradient(135deg,#D97706,#EF4444); color:#fff; border:none; box-shadow:0 4px 16px rgba(239,68,68,0.2); font-family:var(--font-ui); transition:transform 0.15s,box-shadow 0.15s; }
        .btn-book:hover { transform:translateY(-2px); box-shadow:0 8px 24px rgba(239,68,68,0.3); }

        .tabs { padding:0 32px; display:flex; gap:8px; border-bottom:1px solid var(--border-2); margin-top:8px; overflow-x:auto; }
        .tab { padding:12px 16px; font-size:13px; font-weight:700; cursor:pointer; color:var(--muted); border-bottom:2px solid transparent; margin-bottom:-1px; text-transform:uppercase; letter-spacing:.06em; transition:all .2s; white-space:nowrap; }
        .tab.active { color:var(--amber-text); border-bottom-color:var(--amber); }

        .content { flex:1; overflow-y:auto; padding:24px 32px; display:flex; flex-direction:column; gap:16px; }
        .stats-row { display:grid; grid-template-columns:repeat(4,1fr); gap:12px; }
        @media(max-width:768px){ .stats-row{grid-template-columns:1fr 1fr;} .layout{grid-template-columns:1fr;} }
        .stat-card { background:rgba(255,255,255,0.8); border:1px solid var(--border); border-radius:12px; padding:16px; transition:transform 0.2s; }
        .stat-card:hover { transform:translateY(-2px); }
        .stat-label { font-size:11px; text-transform:uppercase; letter-spacing:.1em; color:var(--muted); font-weight:700; margin-bottom:6px; }
        .stat-val { font-size:24px; font-weight:700; line-height:1; }

        .day-row { background:rgba(255,255,255,0.9); border:1px solid var(--border); border-radius:12px; overflow:hidden; transition:all .2s; margin-bottom:12px; }
        .day-row.open { border-color:rgba(245,158,11,0.3); box-shadow:0 8px 24px rgba(0,0,0,0.04); }
        .day-header { display:flex; align-items:center; cursor:pointer; }
        .day-num { width:56px; height:56px; display:flex; align-items:center; justify-content:center; font-weight:700; font-size:15px; border-right:1px solid rgba(0,0,0,0.05); background:rgba(255,255,255,0.5); flex-shrink:0; }
        .day-num.d1{color:var(--amber-text)} .day-num.d2{color:var(--emerald-text)} .day-num.d3{color:var(--amber-text)} .day-num.d4{color:var(--rose)}
        .day-title-wrap { flex:1; padding:0 16px; display:flex; align-items:center; }
        .day-title { font-size:15px; font-weight:700; color:var(--text); }
        .day-chevron { padding:0 20px; color:var(--dim); font-size:14px; transition:transform .3s; flex-shrink:0; }
        .day-chevron.open { transform:rotate(180deg); color:var(--amber-text); }
        .day-body { border-top:1px solid rgba(0,0,0,0.05); display:none; grid-template-columns:1fr 1fr 1fr; background:rgba(255,255,255,0.5); }
        .day-body.open { display:grid; }
        @media(max-width:768px){ .day-body.open{grid-template-columns:1fr;} }
        .day-slot { padding:16px; border-right:1px solid rgba(0,0,0,0.05); }
        .day-slot:last-child { border-right:none; }
        .slot-label { font-size:11px; font-weight:700; letter-spacing:.12em; text-transform:uppercase; margin-bottom:8px; display:flex; align-items:center; gap:6px; }
        .slot-dot { width:6px; height:6px; border-radius:50%; flex-shrink:0; }
        .slot-text { font-size:13px; font-weight:500; color:var(--text); line-height:1.6; }

        .section-head { font-size:11px; font-weight:800; letter-spacing:.12em; text-transform:uppercase; color:var(--dim); margin-bottom:12px; margin-top:8px; }
        .budget-grid { display:grid; grid-template-columns:1fr 1fr; gap:12px; }
        @media(max-width:600px){ .budget-grid{grid-template-columns:1fr;} }
        .budget-row { display:flex; justify-content:space-between; align-items:center; padding:12px 16px; background:rgba(255,255,255,0.8); border:1px solid rgba(0,0,0,0.05); border-radius:8px; }
        .budget-total { grid-column:1/-1; border-color:rgba(16,185,129,0.2); background:var(--emerald-dim); }
      `}} />

      <div className="travel-vibe-bg">
        <div className="orb-1" /><div className="orb-2" /><div className="orb-3" />
      </div>

      <div className="plan-trip-container">

        {showSuccess && !error && (
          <div className="fixed top-6 left-1/2 -translate-x-1/2 z-50 animate-slideDown">
            <div className="bg-emerald-500 text-white px-6 py-3 rounded-xl shadow-xl font-bold flex items-center gap-2">
              🎉 Trip Ready!
            </div>
          </div>
        )}

        {showToast && !error && (
          <div className="fixed bottom-6 right-6 z-50 animate-slideUp">
            <div className="bg-emerald-500 text-white px-5 py-3 rounded-lg shadow-xl font-bold flex items-center gap-2">
              💾 Trip saved successfully!
            </div>
          </div>
        )}

        <div className="shell">
          <div className="topbar">
            <div className="topbar-left">
              <div className="wordmark">wander<span>.</span>ai</div>
              <div className="divider-v" />
              <div className="breadcrumb">
                <button
                  onClick={() => navigate(-1)}
                  style={{ background:"none", border:"none", color:"var(--muted)", cursor:"pointer", fontWeight:"600", fontFamily:"var(--font-ui)" }}
                >
                  Trips
                </button>
                <span style={{ color:"var(--dim)" }}>›</span>
                <b style={{ textTransform:"capitalize" }}>{destination || "New Trip"} · {dayCount} Days</b>
              </div>
            </div>
            <div className="topbar-right">
              {loading
                ? <div className="tag tag-amber loading-pulse" style={{ background:"var(--surface-3)", border:"1px solid var(--border)" }}>Generating...</div>
                : <>
                    <div className="tag tag-emerald"><div className="dot" /> AI Ready</div>
                    <div className="tag tag-amber">{dayCount} Days</div>
                  </>
              }
            </div>
          </div>

          <div className="layout">
            <div className="sidebar">
              <div className="trip-meta">
                <div className="trip-dest">{destination || "Destination"}</div>
                <div className="trip-dates">{startDate} → {endDate}</div>
                <div className="trip-stat">
                  <span className="trip-stat-label">Budget</span>
                  <span className="trip-stat-val" style={{ color:"var(--emerald-text)" }}>₹{budget}</span>
                </div>
                <div className="trip-stat">
                  <span className="trip-stat-label">Days</span>
                  <span className="trip-stat-val">{dayCount}</span>
                </div>
              </div>
              <div className="sidebar-section">
                <div className="sidebar-label">Navigation</div>
                {["Itinerary","Map","Budget","Food & Stays","Tips"].map(tab => (
                  <div
                    key={tab}
                    className={`nav-item ${activeTab === tab ? "active" : ""}`}
                    onClick={() => setActiveTab(tab)}
                  >
                    <div className="nav-icon">
                      <div style={{ width:"6px", height:"6px", borderRadius:"50%", background: activeTab === tab ? "var(--amber)" : "var(--dim)" }} />
                    </div>
                    {tab}
                  </div>
                ))}
              </div>
            </div>

            <div className="main">
              <div className="page-header">
                <div>
                  <div className="page-title">Trip to <span>{destination || "Unknown"}</span></div>
                  <div className="page-sub">
                    {loading || showSuccess
                      ? "AI is crafting your perfect itinerary..."
                      : "Generated by AI · Complete itinerary · Ready to explore"}
                  </div>
                </div>

                {!loading && !error && tripData && (
                  <div className="btn-cluster">
                    <button className="btn-pdf" onClick={downloadPDF}>📄 Download PDF</button>
                    <button className="btn-dashboard" onClick={() => navigate("/dashboard")}>📋 View Dashboard</button>
                    <button className="btn-dashboard" onClick={() => setEditMode(!editMode)}>
                      {editMode ? "❌ Cancel" : "✏️ Edit Trip"}
                    </button>
                    {editMode && (
                      <button className="btn-book" onClick={() => { setTripData(editableTrip); setEditMode(false); }}>
                        💾 Save Changes
                      </button>
                    )}
                    {!editMode && (
                      <button
                        className="btn-book"
                        onClick={() => navigate("/booking", {
                          state: { destination, budget, checkin: startDate, checkout: endDate, tripData }
                        })}
                      >
                        ✈️ Book This Trip →
                      </button>
                    )}
                  </div>
                )}
              </div>

              {/* ✅ UPDATED LOADING SKELETON */}
              {loading && !showSuccess && (
                <div className="content mt-4">
                  <TripSkeleton />
                </div>
              )}

              {!loading && !showSuccess && error && (
                <div className="content" style={{ alignItems:"center", justifyContent:"center" }}>
                  <div style={{ textAlign:"center", background:"var(--rose-dim)", padding:"24px", borderRadius:"12px", border:"1px solid rgba(244,63,94,0.3)" }}>
                    <div style={{ fontSize:"48px", marginBottom:"16px" }}>⚠️</div>
                    <p style={{ color:"var(--text)", fontSize:"16px", fontWeight:"700" }}>{error}</p>
                    <button
                      onClick={() => navigate(-1)}
                      style={{ marginTop:"20px", background:"var(--rose)", color:"#fff", border:"none", padding:"10px 20px", borderRadius:"6px", cursor:"pointer", fontWeight:"600", fontFamily:"var(--font-ui)" }}
                    >
                      Go Back
                    </button>
                  </div>
                </div>
              )}

              {showSuccess && !error && (
                <div className="content" style={{ alignItems:"center", justifyContent:"center" }}>
                  <div style={{ textAlign:"center", background:"rgba(255,255,255,0.9)", padding:"48px", borderRadius:"24px", border:"1px solid rgba(16,185,129,0.3)", boxShadow:"0 20px 40px rgba(0,0,0,0.05)", animation:"popIn 0.5s cubic-bezier(0.16,1,0.3,1)" }}>
                    <div style={{ fontSize:"64px", marginBottom:"16px", animation:"bounceEmoji 1.5s infinite" }}>🎉</div>
                    <h2 style={{ color:"var(--emerald-text)", fontSize:"28px", fontWeight:"800", marginBottom:"8px" }}>Trip Ready!</h2>
                    <p style={{ color:"var(--muted)", fontSize:"15px" }}>Your personalized itinerary is cooked to perfection.</p>
                  </div>
                </div>
              )}

              {!loading && !showSuccess && !error && tripData && (
                <>
                  <div className="tabs">
                    {["Itinerary","Map","Budget","Food & Stays","Tips"].map(tab => (
                      <div key={tab} className={`tab ${activeTab === tab ? "active" : ""}`} onClick={() => setActiveTab(tab)}>
                        {tab}
                      </div>
                    ))}
                  </div>

                  <div className="content">

                    {/* ── MAP TAB USING CUSTOM MAPVIEW COMPONENT ── */}
                    {activeTab === "Map" && (
                      <div className="mt-4">
                        <h2 className="text-xl font-bold mb-4" style={{ color: "var(--text)" }}>🗺️ Map View</h2>
                        <div className="mt-10">
                          <MapView destination={destination} />
                        </div>
                      </div>
                    )}

                    {activeTab === "Itinerary" && (
                      <>
                        <div className="stats-row">
                          <div className="stat-card"><div className="stat-label">Total Days</div><div className="stat-val" style={{color:"var(--amber-text)"}}>{dayCount}</div></div>
                          <div className="stat-card"><div className="stat-label">Total Budget</div><div className="stat-val" style={{color:"var(--emerald-text)"}}>₹{budget}</div></div>
                          <div className="stat-card"><div className="stat-label">Destination</div><div className="stat-val" style={{fontSize:"18px",textTransform:"capitalize",color:"var(--amber-text)"}}>{destination}</div></div>
                          <div className="stat-card"><div className="stat-label">Activities</div><div className="stat-val" style={{color:"var(--rose)"}}>{(tripData.days?.length||0)*3}+</div></div>
                        </div>

                        <div className="section-head">Day-by-day itinerary</div>

                        {tripData.days?.map((day, i) => (
                          <div key={i} className={`day-row ${openDays[i] ? "open" : ""}`}>
                            <div className="day-header" onClick={() => !editMode && toggleDay(i)}>
                              <div className={`day-num d${(i % 4) + 1}`}>D{day.day}</div>
                              <div className="day-title-wrap">
                                {editMode ? (
                                  <input
                                    value={editableTrip?.days[i]?.title || ""}
                                    onChange={(e) => {
                                      const updated = JSON.parse(JSON.stringify(editableTrip));
                                      updated.days[i].title = e.target.value;
                                      setEditableTrip(updated);
                                    }}
                                    onClick={(e) => e.stopPropagation()}
                                    style={{ background:"rgba(255,255,255,0.7)", padding:"4px 12px", borderRadius:"6px", width:"100%", border:"1px solid #d1d5db", fontWeight:"700", outline:"none", fontFamily:"var(--font-ui)" }}
                                  />
                                ) : (
                                  <div className="day-title">{safeString(day.title) || `Exploring ${destination}`}</div>
                                )}
                              </div>
                              <div className={`day-chevron ${openDays[i] ? "open" : ""}`}>▾</div>
                            </div>

                            <div className={`day-body ${openDays[i] ? "open" : ""}`}>
                              {[
                                { key:"morning",   label:"Morning",   dot:"var(--amber)",  text:"var(--amber-text)" },
                                { key:"afternoon", label:"Afternoon", dot:"var(--emerald)",text:"var(--emerald-text)" },
                                { key:"evening",   label:"Evening",   dot:"var(--rose)",   text:"var(--rose)" },
                              ].map(({ key, label, dot, text }) => (
                                <div key={key} className="day-slot">
                                  <div className="slot-label" style={{ color: text }}>
                                    <div className="slot-dot" style={{ background: dot }} />
                                    {label}
                                  </div>
                                  {editMode ? (
                                    <textarea
                                      value={editableTrip?.days[i]?.[key] || ""}
                                      onChange={(e) => {
                                        const updated = JSON.parse(JSON.stringify(editableTrip));
                                        updated.days[i][key] = e.target.value;
                                        setEditableTrip(updated);
                                      }}
                                      style={{ background:"rgba(255,255,255,0.9)", padding:"8px", borderRadius:"6px", width:"100%", border:"1px solid #d1d5db", fontSize:"13px", minHeight:"80px", outline:"none", resize:"vertical", fontFamily:"var(--font-ui)" }}
                                    />
                                  ) : (
                                    <div className="slot-text">{safeString(day[key])}</div>
                                  )}
                                  {!editMode && key === "evening" && day.food?.length > 0 && (
                                    <div style={{ marginTop:"12px", padding:"10px", background:"rgba(245,158,11,0.1)", borderRadius:"6px", border:"1px solid rgba(245,158,11,0.2)" }}>
                                      <b style={{ fontSize:"10px", color:"var(--amber-text)", textTransform:"uppercase", letterSpacing:"0.05em" }}>🍽️ Evening Eats:</b>
                                      {day.food.map((f, fi) => (
                                        <div key={fi} style={{ fontSize:"12px", color:"var(--text)", marginTop:"4px", fontWeight:"500" }}>• {safeString(f)}</div>
                                      ))}
                                    </div>
                                  )}
                                </div>
                              ))}
                            </div>
                          </div>
                        ))}
                      </>
                    )}

                    {activeTab === "Budget" && tripData.budgetBreakdown && (
                      <>
                        <div className="section-head">Budget breakdown</div>
                        <div className="budget-grid">
                          {Object.entries(tripData.budgetBreakdown).map(([key, val]) => (
                            <div key={key} className={`budget-row ${key.toLowerCase().includes("total") ? "budget-total" : ""}`}>
                              <span style={{ textTransform:"capitalize", fontWeight:"600", color:"var(--muted)" }}>
                                {safeString(key).replace(/([A-Z])/g," $1").trim()}
                              </span>
                              <span style={{ fontWeight:"700", color:"var(--emerald-text)" }}>{safeString(val)}</span>
                            </div>
                          ))}
                        </div>
                      </>
                    )}

                    {activeTab === "Food & Stays" && (
                      <>
                        {tripData.whereToStay && (
                          <>
                            <div className="section-head">Where to Stay</div>
                            <div className="budget-grid" style={{ marginBottom:"24px" }}>
                              <div className="budget-row" style={{ flexDirection:"column", alignItems:"flex-start", background:"var(--amber-dim)", borderColor:"rgba(245,158,11,0.3)" }}>
                                <span style={{ color:"var(--amber-text)", marginBottom:"6px", fontWeight:"bold" }}>Budget Option</span>
                                <span style={{ color:"var(--text)" }}>{safeString(tripData.whereToStay.budget || tripData.whereToStay.budgetOption)}</span>
                              </div>
                              <div className="budget-row" style={{ flexDirection:"column", alignItems:"flex-start", background:"var(--emerald-dim)", borderColor:"rgba(16,185,129,0.3)" }}>
                                <span style={{ color:"var(--emerald-text)", marginBottom:"6px", fontWeight:"bold" }}>Mid-Range Option</span>
                                <span style={{ color:"var(--text)" }}>{safeString(tripData.whereToStay.midRange || tripData.whereToStay.midRangeOption)}</span>
                              </div>
                            </div>
                          </>
                        )}
                        {tripData.mustEat?.length > 0 && (
                          <>
                            <div className="section-head">Must-Try Local Foods</div>
                            <div style={{ display:"grid", gridTemplateColumns:"1fr 1fr", gap:"12px" }}>
                              {Array.isArray(tripData.mustEat) ? tripData.mustEat.map((food, i) => (
                                <div key={i} style={{ background:"rgba(255,255,255,0.8)", border:"1px solid rgba(0,0,0,0.05)", borderRadius:"8px", padding:"14px 16px", display:"flex", gap:"12px" }}>
                                  <span style={{ fontSize:"16px" }}>🍜</span>
                                  <span style={{ fontSize:"13px", fontWeight:"500", color:"var(--text)" }}>{safeString(food)}</span>
                                </div>
                              )) : null}
                            </div>
                          </>
                        )}
                      </>
                    )}

                    {activeTab === "Tips" && tripData.travelTips?.length > 0 && (
                      <>
                        <div className="section-head">Essential Travel Tips</div>
                        <div style={{ display:"grid", gap:"12px" }}>
                          {Array.isArray(tripData.travelTips) ? tripData.travelTips.map((tip, i) => (
                            <div key={i} style={{ background:"rgba(255,255,255,0.8)", border:"1px solid rgba(0,0,0,0.05)", borderRadius:"8px", padding:"14px 16px", display:"flex", gap:"12px" }}>
                              <div style={{ fontWeight:"800", color:"var(--muted)", flexShrink:0 }}>0{i+1}</div>
                              <div style={{ fontWeight:"500", color:"var(--text)", lineHeight:"1.6" }}>{safeString(tip)}</div>
                            </div>
                          )) : null}
                        </div>
                      </>
                    )}

                    <div style={{ textAlign:"center", padding:"24px 0", marginTop:"auto" }}>
                      <span style={{ fontSize:"10px", color:"var(--dim)", fontWeight:700, letterSpacing:".15em" }}>
                        GENERATED BY GROQ · WANDER.AI
                      </span>
                    </div>

                  </div>
                </>
              )}
            </div>
          </div>
        </div>
      </div>
    </>
  );
}