// Shared PDF itinerary generator. Used by both PlanTrip and Booking.
// Extracted so both pages produce identical premium PDFs.

const safeString = (val) => {
  if (val === null || val === undefined) return "—";
  if (typeof val === "string") return val;
  if (Array.isArray(val)) return val.map(v => typeof v === 'object' ? Object.values(v).join(' ') : v).join(", ");
  if (typeof val === "object") return Object.values(val).join(", ");
  return String(val);
};

const rgb = (hex) => {
  const h = hex.replace("#","");
  return [parseInt(h.slice(0,2),16), parseInt(h.slice(2,4),16), parseInt(h.slice(4,6),16)];
};

export async function downloadItineraryPDF({ destination, budget, startDate, endDate, tripData, bookingId }) {
  const { default: jsPDF } = await import("jspdf");
  const doc = new jsPDF({ unit: "mm", format: "a4" });
  const PW = 210, PH = 297;
  const ML = 16, MR = 16;
  const CW = PW - ML - MR;

  const plan = tripData && (typeof tripData === "object" ? tripData : (() => {
    try {
      const clean = String(tripData).replace(/^```json\s*/i, "").replace(/^```\s*/i, "").replace(/```\s*$/i, "").trim();
      return JSON.parse(clean);
    } catch { return null; }
  })());

  const safeDayCount = startDate && endDate
    ? Math.max(1, Math.round((new Date(endDate) - new Date(startDate)) / 86400000))
    : (plan?.days?.length || 0);

  const fill   = (hex) => doc.setFillColor(...rgb(hex));
  const stroke = (hex) => doc.setDrawColor(...rgb(hex));
  const color  = (hex) => doc.setTextColor(...rgb(hex));
  const lw     = (w)   => doc.setLineWidth(w);

  let y = 0;
  let pageNum = 1;

  const addFooter = () => {
    color("#9CA3AF"); doc.setFont("helvetica","normal"); doc.setFontSize(8);
    doc.text("Generated by TripNow", ML, PH - 8);
    doc.text(`Page ${pageNum}`, PW - MR, PH - 8, { align: "right" });
  };

  const addPage = () => {
    addFooter();
    doc.addPage();
    pageNum++;
    fill("#FDFBF7"); doc.rect(0, 0, PW, PH, "F");
    color("#9CA3AF"); doc.setFont("helvetica","normal"); doc.setFontSize(8);
    doc.text(`TripNow • ${destination?.toUpperCase() || "ITINERARY"}`, ML, 10);
    y = 18;
  };

  const needSpace = (h) => {
    if (y + h > PH - 15) { addPage(); return true; }
    return false;
  };

  const sectionHead = (text, accentHex = "#D97706") => {
    needSpace(12);
    color(accentHex); doc.setFont("helvetica","bold"); doc.setFontSize(10);
    doc.text(text.toUpperCase(), ML, y);
    y += 2;
    stroke(accentHex); lw(0.5); doc.line(ML, y, ML + CW, y);
    y += 6;
  };

  // ── PAGE 1 ──
  fill("#FDFBF7"); doc.rect(0, 0, PW, PH, "F");
  fill("#FDE68A"); doc.circle(PW, 0, 40, "F");
  fill("#FEF3C7"); doc.circle(0, PH, 50, "F");
  doc.setGState(new doc.GState({ opacity: 0.2 }));
  fill("#FDFBF7"); doc.rect(0, 0, PW, PH, "F");
  doc.setGState(new doc.GState({ opacity: 1 }));

  y = 22;
  color("#B45309"); doc.setFont("helvetica","bold"); doc.setFontSize(8);
  doc.text("TRIPNOW • PERSONALIZED ITINERARY", ML, y);

  y += 10;
  color("#111827"); doc.setFontSize(28);
  doc.text((destination || "TRIP").toUpperCase(), ML, y, { maxWidth: CW });

  y += 8;
  color("#4B5563"); doc.setFont("helvetica","normal"); doc.setFontSize(11);
  doc.text(`${startDate || "—"} to ${endDate || "—"}  •  ${safeDayCount} Days  •  ₹${Number(budget||0).toLocaleString("en-IN")}`, ML, y);

  y += 6;
  stroke("#D1D5DB"); lw(0.3); doc.line(ML, y, ML + CW, y);
  y += 8;

  if (bookingId) {
    color("#9CA3AF"); doc.setFont("helvetica","normal"); doc.setFontSize(8);
    doc.text(`Booking ID: ${bookingId}`, ML, y);
    y += 6;
  }

  // ── BUDGET OVERVIEW ──
  let budgetEntries = [];
  if (plan?.budgetBreakdown) {
    if (Array.isArray(plan.budgetBreakdown)) {
      budgetEntries = plan.budgetBreakdown.map(item => [safeString(item.category || item.name || "Item"), safeString(item.cost || item.amount || "—")]);
    } else if (typeof plan.budgetBreakdown === 'object') {
      budgetEntries = Object.entries(plan.budgetBreakdown);
    }
  }

  if (budgetEntries.length > 0 || plan?.bestTimeToVisit) {
    sectionHead("Trip Overview", "#D97706");
    if (plan?.bestTimeToVisit) {
      color("#111827"); doc.setFont("helvetica","bold"); doc.setFontSize(9);
      doc.text("Best Time to Visit:", ML, y);
      color("#4B5563"); doc.setFont("helvetica","normal");
      doc.text(safeString(plan.bestTimeToVisit), ML + 30, y);
      y += 6;
    }
    if (budgetEntries.length > 0) {
      const halfW = (CW - 4) / 2;
      budgetEntries.forEach(([key, val], idx) => {
        const isLeft = idx % 2 === 0;
        if (isLeft) needSpace(8);
        const xOff = ML + (isLeft ? 0 : halfW + 4);
        const isTotal = key.toLowerCase().includes("total");
        fill(isTotal ? "#FEF3C7" : "#FFFFFF");
        stroke("#E5E7EB"); lw(0.2);
        doc.roundedRect(xOff, y, halfW, 7, 1, 1, "FD");
        color(isTotal ? "#92400E" : "#4B5563");
        doc.setFont("helvetica", isTotal ? "bold" : "normal"); doc.setFontSize(8);
        doc.text(safeString(key).replace(/([A-Z])/g," $1").trim(), xOff + 3, y + 4.8);
        color(isTotal ? "#B45309" : "#111827"); doc.setFont("helvetica","bold");
        doc.text(safeString(val).replace(/₹/g, "Rs. "), xOff + halfW - 3, y + 4.8, { align:"right" });
        if (!isLeft || idx === budgetEntries.length - 1) y += 8;
      });
    }
    y += 4;
  }

  // ── ITINERARY ──
  if (plan?.days?.length) {
    sectionHead("Day-by-Day Itinerary", "#D97706");
    for (const day of plan.days) {
      const mLines = doc.splitTextToSize(safeString(day.morning), CW - 24);
      const aLines = doc.splitTextToSize(safeString(day.afternoon), CW - 24);
      const eLines = doc.splitTextToSize(safeString(day.evening), CW - 24);
      const cardH = 10 + (mLines.length + aLines.length + eLines.length) * 4.2;
      needSpace(cardH + 4);

      fill("#FFFFFF"); stroke("#E5E7EB"); lw(0.3);
      doc.roundedRect(ML, y, CW, cardH, 2, 2, "FD");

      color("#111827"); doc.setFont("helvetica","bold"); doc.setFontSize(9);
      doc.text(`Day ${day.day} — ${day.title || ""}`, ML + 3, y + 5);
      y += 1.5;

      const slot = (label, lines, accent, xOff) => {
        doc.setFontSize(8);
        color(accent); doc.setFont("helvetica","bold");
        doc.text(label, xOff, y + 6);
        doc.setFont("helvetica","normal"); color("#4B5563");
        doc.text(lines, xOff, y + 9, { maxWidth: CW/3 - 8 });
      };

      slot("MORNING", mLines, "#D97706", ML + 4);
      slot("AFTERNOON", aLines, "#2563EB", ML + CW/3);
      slot("EVENING", eLines, "#7C3AED", ML + 2*CW/3);

      y += cardH - 1;
    }

    // ── FOOD & STAYS ──
    if (plan.whereToStay || plan.mustEat?.length) {
      y += 2; sectionHead("Food & Stays", "#D97706");
      if (plan.whereToStay) {
        color("#111827"); doc.setFont("helvetica","bold"); doc.setFontSize(9);
        doc.text("Where to Stay:", ML, y); y += 5;
        color("#4B5563"); doc.setFont("helvetica","normal"); doc.setFontSize(8);
        Object.entries(plan.whereToStay).forEach(([k, v]) => {
          if (v) {
            needSpace(5);
            color("#92400E"); doc.setFont("helvetica","bold"); doc.setFontSize(8);
            doc.text(`${k.charAt(0).toUpperCase() + k.slice(1)}:`, ML, y);
            color("#4B5563"); doc.setFont("helvetica","normal");
            doc.text(safeString(v), ML + 16, y, { maxWidth: CW - 20 });
            y += 4;
          }
        });
      }
      if (plan.mustEat?.length) {
        needSpace(6);
        color("#111827"); doc.setFont("helvetica","bold"); doc.setFontSize(9);
        doc.text("Must-Try Local Food:", ML, y); y += 5;
        plan.mustEat.forEach((item, i) => {
          needSpace(4);
          color("#6B7280"); doc.setFont("helvetica","normal"); doc.setFontSize(8);
          doc.text(`• ${safeString(item)}`, ML + 3, y, { maxWidth: CW - 6 });
          y += 4;
        });
      }
    }

    // ── TRAVEL TIPS ──
    if (plan.travelTips?.length) {
      y += 2; sectionHead("Travel Tips", "#D97706");
      plan.travelTips.forEach((tip, i) => {
        needSpace(5);
        color("#B45309"); doc.setFont("helvetica","bold"); doc.setFontSize(8);
        doc.text(`${i + 1}.`, ML, y);
        color("#4B5563"); doc.setFont("helvetica","normal");
        doc.text(safeString(tip), ML + 6, y, { maxWidth: CW - 10 });
        y += 4;
      });
    }
  }

  addFooter();
  doc.save(`${destination || "trip"}-tripnow-itinerary.pdf`);
}
